apiVersion: v1
kind: ConfigMap
metadata:
  name: newportfolio-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Chandana's Portfolio</title>
    </head>
    <body>
      <h1>Welcome to Chandana's Portfolio!</h1>
      <p>This site is deployed via Kubernetes + Argo CD.</p>
    </body>
    </html>
